-- ==========================================================
-- AGGREGATION QUERIES
-- ==========================================================

-- Question 1:
-- Calculate the total sales generated by the company.
SELECT 
   ROUND(SUM(sales),2)
 FROM orders;

-- Question 2:
-- Calculate the total profit earned by the company.
SELECT 
    ROUND(SUM(profit),2)
FROM orders;

-- Question 3:
-- Find the total number of orders placed.
SELECT 
    count(order_id) as total_orders
FROM orders;

-- Question 4:
-- Calculate the average sales per order.
SELECT 
    ROUND(AVG(sales),2)
FROM orders;

-- Question 5:
-- Find the highest and lowest sales value.
SELECT 
    ROUND(max(sales),2) AS highest_sales,
    ROUND(min(sales),2) AS lowest_sales
FROM orders;

-- Question 6:
-- Calculate the total sales for each product category.
SELECT 
    category,
    ROUND(SUM(profit),2)
FROM orders
GROUP BY category;

-- Question 7:
-- Calculate the total profit for each region.
SELECT 
    category,
    ROUND(SUM(profit),2)
FROM orders
GROUP BY category

-- Question 8:
-- Find the average discount offered for each customer segment.
SELECT 
    segment,
    ROUND(AVG(discount),2)
FROM orders
GROUP BY segment;

-- Question 9:
-- Count the number of orders placed in each ship mode.
SELECT 
    ship_mode,
    count(*) AS total_orders
FROM orders
GROUP BY ship_mode
ORDER BY total_orders DESC

-- Question 10:
-- Calculate the average shipping days for each ship mode.
SELECT 
    ship_mode,
    AVG(shipping_days)
FROM orders
GROUP BY ship_mode